// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/vehicles.proto

package vehicles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleServiceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleServiceError) Reset() {
	*x = VehicleServiceError{}
	mi := &file_proto_vehicles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleServiceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleServiceError) ProtoMessage() {}

func (x *VehicleServiceError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleServiceError.ProtoReflect.Descriptor instead.
func (*VehicleServiceError) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleServiceError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VehicleServiceError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddVehicleModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVehicleModelRequest) Reset() {
	*x = AddVehicleModelRequest{}
	mi := &file_proto_vehicles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVehicleModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVehicleModelRequest) ProtoMessage() {}

func (x *AddVehicleModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVehicleModelRequest.ProtoReflect.Descriptor instead.
func (*AddVehicleModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{1}
}

func (x *AddVehicleModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddVehicleModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVehicleModelResponse) Reset() {
	*x = AddVehicleModelResponse{}
	mi := &file_proto_vehicles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVehicleModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVehicleModelResponse) ProtoMessage() {}

func (x *AddVehicleModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVehicleModelResponse.ProtoReflect.Descriptor instead.
func (*AddVehicleModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{2}
}

func (x *AddVehicleModelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddVehicleModelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddControllerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddControllerRequest) Reset() {
	*x = AddControllerRequest{}
	mi := &file_proto_vehicles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddControllerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddControllerRequest) ProtoMessage() {}

func (x *AddControllerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddControllerRequest.ProtoReflect.Descriptor instead.
func (*AddControllerRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{3}
}

type AddControllerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddControllerResponse) Reset() {
	*x = AddControllerResponse{}
	mi := &file_proto_vehicles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddControllerResponse) ProtoMessage() {}

func (x *AddControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddControllerResponse.ProtoReflect.Descriptor instead.
func (*AddControllerResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{4}
}

type BindControllerToVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	ControllerId  string                 `protobuf:"bytes,2,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindControllerToVehicleRequest) Reset() {
	*x = BindControllerToVehicleRequest{}
	mi := &file_proto_vehicles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindControllerToVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindControllerToVehicleRequest) ProtoMessage() {}

func (x *BindControllerToVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindControllerToVehicleRequest.ProtoReflect.Descriptor instead.
func (*BindControllerToVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{5}
}

func (x *BindControllerToVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *BindControllerToVehicleRequest) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

type BindControllerToVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	ControllerId  string                 `protobuf:"bytes,3,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindControllerToVehicleResponse) Reset() {
	*x = BindControllerToVehicleResponse{}
	mi := &file_proto_vehicles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindControllerToVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindControllerToVehicleResponse) ProtoMessage() {}

func (x *BindControllerToVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindControllerToVehicleResponse.ProtoReflect.Descriptor instead.
func (*BindControllerToVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{6}
}

func (x *BindControllerToVehicleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BindControllerToVehicleResponse) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *BindControllerToVehicleResponse) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *BindControllerToVehicleResponse) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *BindControllerToVehicleResponse) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type AddVehicleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ModelId            string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ChassisNumber      string                 `protobuf:"bytes,2,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,3,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddVehicleRequest) Reset() {
	*x = AddVehicleRequest{}
	mi := &file_proto_vehicles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVehicleRequest) ProtoMessage() {}

func (x *AddVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVehicleRequest.ProtoReflect.Descriptor instead.
func (*AddVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{7}
}

func (x *AddVehicleRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AddVehicleRequest) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *AddVehicleRequest) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

type AddVehicleResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelId            string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ChassisNumber      string                 `protobuf:"bytes,3,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,4,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	Error              *VehicleServiceError   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddVehicleResponse) Reset() {
	*x = AddVehicleResponse{}
	mi := &file_proto_vehicles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVehicleResponse) ProtoMessage() {}

func (x *AddVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVehicleResponse.ProtoReflect.Descriptor instead.
func (*AddVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicles_proto_rawDescGZIP(), []int{8}
}

func (x *AddVehicleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddVehicleResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AddVehicleResponse) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *AddVehicleResponse) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *AddVehicleResponse) GetError() *VehicleServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_vehicles_proto protoreflect.FileDescriptor

const file_proto_vehicles_proto_rawDesc = "" +
	"\n" +
	"\x14proto/vehicles.proto\x12\bvehicles\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x13VehicleServiceError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x16AddVehicleModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\x17AddVehicleModelResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x16\n" +
	"\x14AddControllerRequest\"\x17\n" +
	"\x15AddControllerResponse\"d\n" +
	"\x1eBindControllerToVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12#\n" +
	"\rcontroller_id\x18\x02 \x01(\tR\fcontrollerId\"\xe7\x01\n" +
	"\x1fBindControllerToVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12#\n" +
	"\rcontroller_id\x18\x03 \x01(\tR\fcontrollerId\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x86\x01\n" +
	"\x11AddVehicleRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12%\n" +
	"\x0echassis_number\x18\x02 \x01(\tR\rchassisNumber\x12/\n" +
	"\x13registration_number\x18\x03 \x01(\tR\x12registrationNumber\"\xcc\x01\n" +
	"\x12AddVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12%\n" +
	"\x0echassis_number\x18\x03 \x01(\tR\rchassisNumber\x12/\n" +
	"\x13registration_number\x18\x04 \x01(\tR\x12registrationNumber\x123\n" +
	"\x05error\x18\x05 \x01(\v2\x1d.vehicles.VehicleServiceErrorR\x05error2\xf4\x02\n" +
	"\x0fVehiclesService\x12V\n" +
	"\x0fAddVehicleModel\x12 .vehicles.AddVehicleModelRequest\x1a!.vehicles.AddVehicleModelResponse\x12G\n" +
	"\n" +
	"AddVehicle\x12\x1b.vehicles.AddVehicleRequest\x1a\x1c.vehicles.AddVehicleResponse\x12P\n" +
	"\rAddController\x12\x1e.vehicles.AddControllerRequest\x1a\x1f.vehicles.AddControllerResponse\x12n\n" +
	"\x17BindControllerToVehicle\x12(.vehicles.BindControllerToVehicleRequest\x1a).vehicles.BindControllerToVehicleResponseB\fZ\n" +
	"./vehiclesb\x06proto3"

var (
	file_proto_vehicles_proto_rawDescOnce sync.Once
	file_proto_vehicles_proto_rawDescData []byte
)

func file_proto_vehicles_proto_rawDescGZIP() []byte {
	file_proto_vehicles_proto_rawDescOnce.Do(func() {
		file_proto_vehicles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vehicles_proto_rawDesc), len(file_proto_vehicles_proto_rawDesc)))
	})
	return file_proto_vehicles_proto_rawDescData
}

var file_proto_vehicles_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_vehicles_proto_goTypes = []any{
	(*VehicleServiceError)(nil),             // 0: vehicles.VehicleServiceError
	(*AddVehicleModelRequest)(nil),          // 1: vehicles.AddVehicleModelRequest
	(*AddVehicleModelResponse)(nil),         // 2: vehicles.AddVehicleModelResponse
	(*AddControllerRequest)(nil),            // 3: vehicles.AddControllerRequest
	(*AddControllerResponse)(nil),           // 4: vehicles.AddControllerResponse
	(*BindControllerToVehicleRequest)(nil),  // 5: vehicles.BindControllerToVehicleRequest
	(*BindControllerToVehicleResponse)(nil), // 6: vehicles.BindControllerToVehicleResponse
	(*AddVehicleRequest)(nil),               // 7: vehicles.AddVehicleRequest
	(*AddVehicleResponse)(nil),              // 8: vehicles.AddVehicleResponse
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
}
var file_proto_vehicles_proto_depIdxs = []int32{
	9, // 0: vehicles.BindControllerToVehicleResponse.start_date:type_name -> google.protobuf.Timestamp
	9, // 1: vehicles.BindControllerToVehicleResponse.end_date:type_name -> google.protobuf.Timestamp
	0, // 2: vehicles.AddVehicleResponse.error:type_name -> vehicles.VehicleServiceError
	1, // 3: vehicles.VehiclesService.AddVehicleModel:input_type -> vehicles.AddVehicleModelRequest
	7, // 4: vehicles.VehiclesService.AddVehicle:input_type -> vehicles.AddVehicleRequest
	3, // 5: vehicles.VehiclesService.AddController:input_type -> vehicles.AddControllerRequest
	5, // 6: vehicles.VehiclesService.BindControllerToVehicle:input_type -> vehicles.BindControllerToVehicleRequest
	2, // 7: vehicles.VehiclesService.AddVehicleModel:output_type -> vehicles.AddVehicleModelResponse
	8, // 8: vehicles.VehiclesService.AddVehicle:output_type -> vehicles.AddVehicleResponse
	4, // 9: vehicles.VehiclesService.AddController:output_type -> vehicles.AddControllerResponse
	6, // 10: vehicles.VehiclesService.BindControllerToVehicle:output_type -> vehicles.BindControllerToVehicleResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_vehicles_proto_init() }
func file_proto_vehicles_proto_init() {
	if File_proto_vehicles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vehicles_proto_rawDesc), len(file_proto_vehicles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vehicles_proto_goTypes,
		DependencyIndexes: file_proto_vehicles_proto_depIdxs,
		MessageInfos:      file_proto_vehicles_proto_msgTypes,
	}.Build()
	File_proto_vehicles_proto = out.File
	file_proto_vehicles_proto_goTypes = nil
	file_proto_vehicles_proto_depIdxs = nil
}
